name: publish-to-staging

on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Checkout veesquared.github.io
      uses: actions/checkout@v4
      with:
        repository: veesquared/veesquared.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
        path: staging
    - run: | 
        git config --global user.name "github-actions"
        git config --global user.email "12947066+VeeSquared@users.noreply.github.com"
        cd staging
        git fetch
        git switch staging
        rm -r *
        cp -a ../dist/. ./
        touch tmpfile
        git diff --name-only > tmpfile
        minimumsize=0
        tempfilesize=$(wc -c <"tmpfile")
        if [ $tempfilesize -gt $minimumsize ]; then
        echo tempfilesize = $tempfilesize
        rm tmpfile
        git add .
        git commit -m "Automated Deploy to Staging - RunId-"${{ github.run_id }}
        git push
        fi